### PR TITLE
Feat/es5 polyfill

### PR DESCRIPTION
**Pull request by w33ble**
Closes https://github.com/elastic/tinymath/issues/29

- Split up build and dev rollup bundles
  - Do less building in dev mode
- Add es5 polyfill build
  - Works with IE11

In order to not balloon the size of the bundles provided, I opted to build the es5 version as another bundle, which can be used if IE11 support is desired. The two polyfills required nearly double the size of the bundles. 

Usage: `import { evaluate, parse } from 'tinymath/lib/tinymath.es5.js';`

screenshot 2018-03-13 13 03 00
[source for above](https://gist.github.com/anonymous/d5fe808caa49fe0c963ba2cc28020bfb)

The other builds require ES6/ES2015 support, just like they did before.

### CODE REVIEW

**Comment by w33ble** [comment]
@rashidkpc are you OK shipping es5 support as a different bundle like this? It's basically what we already had, but now we have a bundle that supports old browsers (namely, IE11).

**Comment by rashidkpc** [comment]
Is there any reason to ship es5 support as a different bundle as opposed to just shipping one? What is the easiest way to integrate this current approach into Canvas?

**Comment by w33ble** [comment]
> Is there any reason to ship es5 support as a different bundle as opposed to just shipping one?

Smaller bundles. Most projects that use tinymath will have their own build process (canvas, kibana), so they don't need the es5 build. The es5 version is mostly there for convenience for anyone *not* doing their own build.

> What is the easiest way to integrate this current approach into Canvas?

We change nothing. Canvas does its own building (via Kibana).

**Comment by rashidkpc** [comment]
Works for me, LGTM

**Pull request merged**
